

using AutoGeneratedClass;
using System;

namespace maind;

[GenerateDto]
public class Anas
{
    public string? Id { get; set; }


}
public class GeneratedClass
{
    public int Id { get; set; }
    public string Name { get; set; }

    public GeneratedClass (int id, string name)
    {
        Id = id;
        Name = name;
    }

    public void Display()
    {
        Console.WriteLine($"ID: {Id}, Name: {Name}");
    }
}